
use_frameworks!

platform :ios, '13.0'

target 'WDFrameWorkIOS_Example' do
  use_frameworks!
  pod 'WDFrameWorkIOS', :path => '../'
  pod 'Alamofire', :git => 'https://github.com/Mohamed-AbdulRaouf/Alamofire.git', :commit => '78424be314842833c04bc3bef5b72e85fff99204'
  target 'WDFrameWorkIOS_Tests' do
    inherit! :search_paths
    
    
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  end
end
