//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let RBLL = _RBLL(bundle: Bundle(for: BundleFinder.self))

struct _RBLL {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var file: file { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 86 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: Connection error
      ///
      /// Key: Connection_error_title
      ///
      /// Locales: en, ar
      var connection_error_title: RswiftResources.StringResource { .init(key: "Connection_error_title", tableName: "Localizable", source: source, developmentValue: "Connection error", comment: nil) }

      /// en translation: Internet connection is lost. Move to a location where more stable connection is available, or wait until the connection returns to be stable.
      ///
      /// Key: NetworkError_ConnectionLost
      ///
      /// Locales: en, ar
      var networkError_ConnectionLost: RswiftResources.StringResource { .init(key: "NetworkError_ConnectionLost", tableName: "Localizable", source: source, developmentValue: "Internet connection is lost. Move to a location where more stable connection is available, or wait until the connection returns to be stable.", comment: nil) }

      /// en translation: Incorrect data returned from Pixabay server. Try again, or wait until Pixabay fixes the problem.
      ///
      /// Key: NetworkError_IncorrectDataReturned
      ///
      /// Locales: en, ar
      var networkError_IncorrectDataReturned: RswiftResources.StringResource { .init(key: "NetworkError_IncorrectDataReturned", tableName: "Localizable", source: source, developmentValue: "Incorrect data returned from Pixabay server. Try again, or wait until Pixabay fixes the problem.", comment: nil) }

      /// en translation: International roaming is not allowed. Change the international roaming setting, or turn on Wi-Fi.
      ///
      /// Key: NetworkError_InternationalRoamingOff
      ///
      /// Locales: en, ar
      var networkError_InternationalRoamingOff: RswiftResources.StringResource { .init(key: "NetworkError_InternationalRoamingOff", tableName: "Localizable", source: source, developmentValue: "International roaming is not allowed. Change the international roaming setting, or turn on Wi-Fi.", comment: nil) }

      /// en translation: Not connected to the internet. Turn on Wi-Fi, or allow cellular data connection.
      ///
      /// Key: NetworkError_NotConnectedToInternet
      ///
      /// Locales: en, ar
      var networkError_NotConnectedToInternet: RswiftResources.StringResource { .init(key: "NetworkError_NotConnectedToInternet", tableName: "Localizable", source: source, developmentValue: "Not connected to the internet. Turn on Wi-Fi, or allow cellular data connection.", comment: nil) }

      /// en translation: Could not reach the Pixabay server. Check the internet connection, or wait until the server becomes accessible.
      ///
      /// Key: NetworkError_NotReachedServer
      ///
      /// Locales: en, ar
      var networkError_NotReachedServer: RswiftResources.StringResource { .init(key: "NetworkError_NotReachedServer", tableName: "Localizable", source: source, developmentValue: "Could not reach the Pixabay server. Check the internet connection, or wait until the server becomes accessible.", comment: nil) }

      /// en translation: Unknown error occurred. Check internet connection and try again.
      ///
      /// Key: NetworkError_Unknown
      ///
      /// Locales: en, ar
      var networkError_Unknown: RswiftResources.StringResource { .init(key: "NetworkError_Unknown", tableName: "Localizable", source: source, developmentValue: "Unknown error occurred. Check internet connection and try again.", comment: nil) }

      /// en translation: All
      ///
      /// Key: all_service
      ///
      /// Locales: en, ar
      var all_service: RswiftResources.StringResource { .init(key: "all_service", tableName: "Localizable", source: source, developmentValue: "All", comment: nil) }

      /// en translation: Branch Not Available.
      ///
      /// Key: branch_not_available
      ///
      /// Locales: en, ar
      var branch_not_available: RswiftResources.StringResource { .init(key: "branch_not_available", tableName: "Localizable", source: source, developmentValue: "Branch Not Available.", comment: nil) }

      /// en translation: You Can't Use Two Discount Types.
      ///
      /// Key: can_not_use_two_type
      ///
      /// Locales: en, ar
      var can_not_use_two_type: RswiftResources.StringResource { .init(key: "can_not_use_two_type", tableName: "Localizable", source: source, developmentValue: "You Can't Use Two Discount Types.", comment: nil) }

      /// en translation: Your Order Number is Used Before.
      ///
      /// Key: code_used_before
      ///
      /// Locales: en, ar
      var code_used_before: RswiftResources.StringResource { .init(key: "code_used_before", tableName: "Localizable", source: source, developmentValue: "Your Order Number is Used Before.", comment: nil) }

      /// en translation: Your Discount Is Exceeding Maximum Allowed Limit.
      ///
      /// Key: coupon_code_exceeding_maximum
      ///
      /// Locales: en, ar
      var coupon_code_exceeding_maximum: RswiftResources.StringResource { .init(key: "coupon_code_exceeding_maximum", tableName: "Localizable", source: source, developmentValue: "Your Discount Is Exceeding Maximum Allowed Limit.", comment: nil) }

      /// en translation: Coupon Code Is Assigned To Another User.
      ///
      /// Key: coupon_code_is_assigned_to_another_one
      ///
      /// Locales: en, ar
      var coupon_code_is_assigned_to_another_one: RswiftResources.StringResource { .init(key: "coupon_code_is_assigned_to_another_one", tableName: "Localizable", source: source, developmentValue: "Coupon Code Is Assigned To Another User.", comment: nil) }

      /// en translation: Coupon Code Is Expired.
      ///
      /// Key: coupon_code_is_expired
      ///
      /// Locales: en, ar
      var coupon_code_is_expired: RswiftResources.StringResource { .init(key: "coupon_code_is_expired", tableName: "Localizable", source: source, developmentValue: "Coupon Code Is Expired.", comment: nil) }

      /// en translation: Coupon Code Is Invalid.
      ///
      /// Key: coupon_code_not_correct
      ///
      /// Locales: en, ar
      var coupon_code_not_correct: RswiftResources.StringResource { .init(key: "coupon_code_not_correct", tableName: "Localizable", source: source, developmentValue: "Coupon Code Is Invalid.", comment: nil) }

      /// en translation: Coupon Code Not In Campaign.
      ///
      /// Key: coupon_code_not_in_campaign
      ///
      /// Locales: en, ar
      var coupon_code_not_in_campaign: RswiftResources.StringResource { .init(key: "coupon_code_not_in_campaign", tableName: "Localizable", source: source, developmentValue: "Coupon Code Not In Campaign.", comment: nil) }

      /// en translation: You don't have points enough.
      ///
      /// Key: coupon_code_points_enough
      ///
      /// Locales: en, ar
      var coupon_code_points_enough: RswiftResources.StringResource { .init(key: "coupon_code_points_enough", tableName: "Localizable", source: source, developmentValue: "You don't have points enough.", comment: nil) }

      /// en translation: Coupon Code Already Used Before.
      ///
      /// Key: coupon_code_used_before
      ///
      /// Locales: en, ar
      var coupon_code_used_before: RswiftResources.StringResource { .init(key: "coupon_code_used_before", tableName: "Localizable", source: source, developmentValue: "Coupon Code Already Used Before.", comment: nil) }

      /// en translation: Customer Already Registered To this Brand
      ///
      /// Key: customer_register_before_to_brand
      ///
      /// Locales: en, ar
      var customer_register_before_to_brand: RswiftResources.StringResource { .init(key: "customer_register_before_to_brand", tableName: "Localizable", source: source, developmentValue: "Customer Already Registered To this Brand", comment: nil) }

      /// en translation: Customer Already Registered To this Brand
      ///
      /// Key: customer_registered_to_brand_before
      ///
      /// Locales: en, ar
      var customer_registered_to_brand_before: RswiftResources.StringResource { .init(key: "customer_registered_to_brand_before", tableName: "Localizable", source: source, developmentValue: "Customer Already Registered To this Brand", comment: nil) }

      /// en translation: Email already exists
      ///
      /// Key: email_address_exist
      ///
      /// Locales: en, ar
      var email_address_exist: RswiftResources.StringResource { .init(key: "email_address_exist", tableName: "Localizable", source: source, developmentValue: "Email already exists", comment: nil) }

      /// en translation: Empty Building No
      ///
      /// Key: empty_building_no
      ///
      /// Locales: en, ar
      var empty_building_no: RswiftResources.StringResource { .init(key: "empty_building_no", tableName: "Localizable", source: source, developmentValue: "Empty Building No", comment: nil) }

      /// en translation: CVV is required!
      ///
      /// Key: empty_card_cvv
      ///
      /// Locales: en, ar
      var empty_card_cvv: RswiftResources.StringResource { .init(key: "empty_card_cvv", tableName: "Localizable", source: source, developmentValue: "CVV is required!", comment: nil) }

      /// en translation: Expiry date required!
      ///
      /// Key: empty_card_expiry_date
      ///
      /// Locales: en, ar
      var empty_card_expiry_date: RswiftResources.StringResource { .init(key: "empty_card_expiry_date", tableName: "Localizable", source: source, developmentValue: "Expiry date required!", comment: nil) }

      /// en translation: Holder name is required!
      ///
      /// Key: empty_card_name
      ///
      /// Locales: en, ar
      var empty_card_name: RswiftResources.StringResource { .init(key: "empty_card_name", tableName: "Localizable", source: source, developmentValue: "Holder name is required!", comment: nil) }

      /// en translation: Please enter your cardData number!
      ///
      /// Key: empty_card_number
      ///
      /// Locales: en, ar
      var empty_card_number: RswiftResources.StringResource { .init(key: "empty_card_number", tableName: "Localizable", source: source, developmentValue: "Please enter your cardData number!", comment: nil) }

      /// en translation: Please enter your Email Address
      ///
      /// Key: empty_email
      ///
      /// Locales: en, ar
      var empty_email: RswiftResources.StringResource { .init(key: "empty_email", tableName: "Localizable", source: source, developmentValue: "Please enter your Email Address", comment: nil) }

      /// en translation: This field is required
      ///
      /// Key: empty_field
      ///
      /// Locales: en, ar
      var empty_field: RswiftResources.StringResource { .init(key: "empty_field", tableName: "Localizable", source: source, developmentValue: "This field is required", comment: nil) }

      /// en translation: Empty Floor No.
      ///
      /// Key: empty_floor_no
      ///
      /// Locales: en, ar
      var empty_floor_no: RswiftResources.StringResource { .init(key: "empty_floor_no", tableName: "Localizable", source: source, developmentValue: "Empty Floor No.", comment: nil) }

      /// en translation: Please enter your Last Name
      ///
      /// Key: empty_last_name
      ///
      /// Locales: en, ar
      var empty_last_name: RswiftResources.StringResource { .init(key: "empty_last_name", tableName: "Localizable", source: source, developmentValue: "Please enter your Last Name", comment: nil) }

      /// en translation: Please enter your  Name
      ///
      /// Key: empty_name
      ///
      /// Locales: en, ar
      var empty_name: RswiftResources.StringResource { .init(key: "empty_name", tableName: "Localizable", source: source, developmentValue: "Please enter your  Name", comment: nil) }

      /// en translation: Please enter password
      ///
      /// Key: empty_password
      ///
      /// Locales: en, ar
      var empty_password: RswiftResources.StringResource { .init(key: "empty_password", tableName: "Localizable", source: source, developmentValue: "Please enter password", comment: nil) }

      /// en translation: Please enter mobile Number
      ///
      /// Key: empty_phone_number
      ///
      /// Locales: en, ar
      var empty_phone_number: RswiftResources.StringResource { .init(key: "empty_phone_number", tableName: "Localizable", source: source, developmentValue: "Please enter mobile Number", comment: nil) }

      /// en translation: Empty Referral Code
      ///
      /// Key: empty_referral_code
      ///
      /// Locales: en, ar
      var empty_referral_code: RswiftResources.StringResource { .init(key: "empty_referral_code", tableName: "Localizable", source: source, developmentValue: "Empty Referral Code", comment: nil) }

      /// en translation: Empty Street Name
      ///
      /// Key: empty_street_name
      ///
      /// Locales: en, ar
      var empty_street_name: RswiftResources.StringResource { .init(key: "empty_street_name", tableName: "Localizable", source: source, developmentValue: "Empty Street Name", comment: nil) }

      /// en translation: Please select address
      ///
      /// Key: empty_user_address_id
      ///
      /// Locales: en, ar
      var empty_user_address_id: RswiftResources.StringResource { .init(key: "empty_user_address_id", tableName: "Localizable", source: source, developmentValue: "Please select address", comment: nil) }

      /// en translation: Empty Verification Code
      ///
      /// Key: empty_verification_code
      ///
      /// Locales: en, ar
      var empty_verification_code: RswiftResources.StringResource { .init(key: "empty_verification_code", tableName: "Localizable", source: source, developmentValue: "Empty Verification Code", comment: nil) }

      /// en translation: Please enter Verification Code
      ///
      /// Key: empty_verify_code
      ///
      /// Locales: en, ar
      var empty_verify_code: RswiftResources.StringResource { .init(key: "empty_verify_code", tableName: "Localizable", source: source, developmentValue: "Please enter Verification Code", comment: nil) }

      /// en translation: Some error occure
      ///
      /// Key: error_occure
      ///
      /// Locales: en, ar
      var error_occure: RswiftResources.StringResource { .init(key: "error_occure", tableName: "Localizable", source: source, developmentValue: "Some error occure", comment: nil) }

      /// en translation: Online Ordering Is Not Available .
      ///
      /// Key: error_online_order_msg
      ///
      /// Locales: en, ar
      var error_online_order_msg: RswiftResources.StringResource { .init(key: "error_online_order_msg", tableName: "Localizable", source: source, developmentValue: "Online Ordering Is Not Available .", comment: nil) }

      /// en translation: Expired Card
      ///
      /// Key: expired_card
      ///
      /// Locales: en, ar
      var expired_card: RswiftResources.StringResource { .init(key: "expired_card", tableName: "Localizable", source: source, developmentValue: "Expired Card", comment: nil) }

      /// en translation: Faild to Parse Data
      ///
      /// Key: faild_parse_data
      ///
      /// Locales: en, ar
      var faild_parse_data: RswiftResources.StringResource { .init(key: "faild_parse_data", tableName: "Localizable", source: source, developmentValue: "Faild to Parse Data", comment: nil) }

      /// en translation: Customer Registered To Brand Failed
      ///
      /// Key: faild_register_to_brand
      ///
      /// Locales: en, ar
      var faild_register_to_brand: RswiftResources.StringResource { .init(key: "faild_register_to_brand", tableName: "Localizable", source: source, developmentValue: "Customer Registered To Brand Failed", comment: nil) }

      /// en translation: Failed Send Verify Code.
      ///
      /// Key: faild_send_verify_code
      ///
      /// Locales: en, ar
      var faild_send_verify_code: RswiftResources.StringResource { .init(key: "faild_send_verify_code", tableName: "Localizable", source: source, developmentValue: "Failed Send Verify Code.", comment: nil) }

      /// en translation: Failed to Update Verify Code.
      ///
      /// Key: faild_update_verify_code
      ///
      /// Locales: en, ar
      var faild_update_verify_code: RswiftResources.StringResource { .init(key: "faild_update_verify_code", tableName: "Localizable", source: source, developmentValue: "Failed to Update Verify Code.", comment: nil) }

      /// en translation: Faild to update password
      ///
      /// Key: faild_upfate_password
      ///
      /// Locales: en, ar
      var faild_upfate_password: RswiftResources.StringResource { .init(key: "faild_upfate_password", tableName: "Localizable", source: source, developmentValue: "Faild to update password", comment: nil) }

      /// en translation: Failed Validate Customer
      ///
      /// Key: failed_validate_customer
      ///
      /// Locales: en, ar
      var failed_validate_customer: RswiftResources.StringResource { .init(key: "failed_validate_customer", tableName: "Localizable", source: source, developmentValue: "Failed Validate Customer", comment: nil) }

      /// en translation: Your Account is Inactive , you can't login with this Phone Number
      ///
      /// Key: inactive_account
      ///
      /// Locales: en, ar
      var inactive_account: RswiftResources.StringResource { .init(key: "inactive_account", tableName: "Localizable", source: source, developmentValue: "Your Account is Inactive , you can't login with this Phone Number", comment: nil) }

      /// en translation: Invalid Building NO
      ///
      /// Key: invalid_building_no
      ///
      /// Locales: en, ar
      var invalid_building_no: RswiftResources.StringResource { .init(key: "invalid_building_no", tableName: "Localizable", source: source, developmentValue: "Invalid Building NO", comment: nil) }

      /// en translation: Invalid Card CVV
      ///
      /// Key: invalid_card_cvv
      ///
      /// Locales: en, ar
      var invalid_card_cvv: RswiftResources.StringResource { .init(key: "invalid_card_cvv", tableName: "Localizable", source: source, developmentValue: "Invalid Card CVV", comment: nil) }

      /// en translation: Invalid Expiry Date
      ///
      /// Key: invalid_card_expiry_date
      ///
      /// Locales: en, ar
      var invalid_card_expiry_date: RswiftResources.StringResource { .init(key: "invalid_card_expiry_date", tableName: "Localizable", source: source, developmentValue: "Invalid Expiry Date", comment: nil) }

      /// en translation: Invalid Card Name
      ///
      /// Key: invalid_card_name
      ///
      /// Locales: en, ar
      var invalid_card_name: RswiftResources.StringResource { .init(key: "invalid_card_name", tableName: "Localizable", source: source, developmentValue: "Invalid Card Name", comment: nil) }

      /// en translation: Invalid Card Number
      ///
      /// Key: invalid_card_number
      ///
      /// Locales: en, ar
      var invalid_card_number: RswiftResources.StringResource { .init(key: "invalid_card_number", tableName: "Localizable", source: source, developmentValue: "Invalid Card Number", comment: nil) }

      /// en translation: Invalid Customer Source
      ///
      /// Key: invalid_customer_source
      ///
      /// Locales: en, ar
      var invalid_customer_source: RswiftResources.StringResource { .init(key: "invalid_customer_source", tableName: "Localizable", source: source, developmentValue: "Invalid Customer Source", comment: nil) }

      /// en translation: Invalid Email Address.
      ///
      /// Key: invalid_email_address
      ///
      /// Locales: en, ar
      var invalid_email_address: RswiftResources.StringResource { .init(key: "invalid_email_address", tableName: "Localizable", source: source, developmentValue: "Invalid Email Address.", comment: nil) }

      /// en translation: Invalid First Name
      ///
      /// Key: invalid_first_name
      ///
      /// Locales: en, ar
      var invalid_first_name: RswiftResources.StringResource { .init(key: "invalid_first_name", tableName: "Localizable", source: source, developmentValue: "Invalid First Name", comment: nil) }

      /// en translation: Invalid Floor no.
      ///
      /// Key: invalid_floor_no
      ///
      /// Locales: en, ar
      var invalid_floor_no: RswiftResources.StringResource { .init(key: "invalid_floor_no", tableName: "Localizable", source: source, developmentValue: "Invalid Floor no.", comment: nil) }

      /// en translation: Invalid Gender
      ///
      /// Key: invalid_gender
      ///
      /// Locales: en, ar
      var invalid_gender: RswiftResources.StringResource { .init(key: "invalid_gender", tableName: "Localizable", source: source, developmentValue: "Invalid Gender", comment: nil) }

      /// en translation: Invalid ID
      ///
      /// Key: invalid_id
      ///
      /// Locales: en, ar
      var invalid_id: RswiftResources.StringResource { .init(key: "invalid_id", tableName: "Localizable", source: source, developmentValue: "Invalid ID", comment: nil) }

      /// en translation: Invalid Input Data.
      ///
      /// Key: invalid_input_data
      ///
      /// Locales: en, ar
      var invalid_input_data: RswiftResources.StringResource { .init(key: "invalid_input_data", tableName: "Localizable", source: source, developmentValue: "Invalid Input Data.", comment: nil) }

      /// en translation: Invalid Last Name.
      ///
      /// Key: invalid_last_name
      ///
      /// Locales: en, ar
      var invalid_last_name: RswiftResources.StringResource { .init(key: "invalid_last_name", tableName: "Localizable", source: source, developmentValue: "Invalid Last Name.", comment: nil) }

      /// en translation: Invalid Mobile Language
      ///
      /// Key: invalid_mobile_language
      ///
      /// Locales: en, ar
      var invalid_mobile_language: RswiftResources.StringResource { .init(key: "invalid_mobile_language", tableName: "Localizable", source: source, developmentValue: "Invalid Mobile Language", comment: nil) }

      /// en translation: Invalid Mobile App Token.
      ///
      /// Key: invalid_mobile_token
      ///
      /// Locales: en, ar
      var invalid_mobile_token: RswiftResources.StringResource { .init(key: "invalid_mobile_token", tableName: "Localizable", source: source, developmentValue: "Invalid Mobile App Token.", comment: nil) }

      /// en translation: Invalid Password.
      ///
      /// Key: invalid_password
      ///
      /// Locales: en, ar
      var invalid_password: RswiftResources.StringResource { .init(key: "invalid_password", tableName: "Localizable", source: source, developmentValue: "Invalid Password.", comment: nil) }

      /// en translation: Password Length must be greater than %@ and Less than %@
      ///
      /// Key: invalid_password_length
      ///
      /// Locales: en, ar
      var invalid_password_length: RswiftResources.StringResource2<String, String> { .init(key: "invalid_password_length", tableName: "Localizable", source: source, developmentValue: "Password Length must be greater than %@ and Less than %@", comment: nil) }

      /// en translation: Invalid phone number
      ///
      /// Key: invalid_phone_number
      ///
      /// Locales: en, ar
      var invalid_phone_number: RswiftResources.StringResource { .init(key: "invalid_phone_number", tableName: "Localizable", source: source, developmentValue: "Invalid phone number", comment: nil) }

      /// en translation: Invalid QR Code
      ///
      /// Key: invalid_qr_code
      ///
      /// Locales: en, ar
      var invalid_qr_code: RswiftResources.StringResource { .init(key: "invalid_qr_code", tableName: "Localizable", source: source, developmentValue: "Invalid QR Code", comment: nil) }

      /// en translation: Please at least rate one
      ///
      /// Key: invalid_rate
      ///
      /// Locales: en, ar
      var invalid_rate: RswiftResources.StringResource { .init(key: "invalid_rate", tableName: "Localizable", source: source, developmentValue: "Please at least rate one", comment: nil) }

      /// en translation: Invalid Referral code
      ///
      /// Key: invalid_referral_code
      ///
      /// Locales: en, ar
      var invalid_referral_code: RswiftResources.StringResource { .init(key: "invalid_referral_code", tableName: "Localizable", source: source, developmentValue: "Invalid Referral code", comment: nil) }

      /// en translation: Invalid share code
      ///
      /// Key: invalid_share_code
      ///
      /// Locales: en, ar
      var invalid_share_code: RswiftResources.StringResource { .init(key: "invalid_share_code", tableName: "Localizable", source: source, developmentValue: "Invalid share code", comment: nil) }

      /// en translation: Invalid Street Name
      ///
      /// Key: invalid_street_name
      ///
      /// Locales: en, ar
      var invalid_street_name: RswiftResources.StringResource { .init(key: "invalid_street_name", tableName: "Localizable", source: source, developmentValue: "Invalid Street Name", comment: nil) }

      /// en translation: Invalid Verification Code
      ///
      /// Key: invalid_verification_code
      ///
      /// Locales: en, ar
      var invalid_verification_code: RswiftResources.StringResource { .init(key: "invalid_verification_code", tableName: "Localizable", source: source, developmentValue: "Invalid Verification Code", comment: nil) }

      /// en translation: Some of the items in the cart have been modified or updated.Your cart will be emptied
      ///
      /// Key: items_changed
      ///
      /// Locales: en, ar
      var items_changed: RswiftResources.StringResource { .init(key: "items_changed", tableName: "Localizable", source: source, developmentValue: "Some of the items in the cart have been modified or updated.Your cart will be emptied", comment: nil) }

      /// en translation: Your total order amount is less than  the minimum value for delivery
      ///
      /// Key: min_order_invalid
      ///
      /// Locales: en, ar
      var min_order_invalid: RswiftResources.StringResource { .init(key: "min_order_invalid", tableName: "Localizable", source: source, developmentValue: "Your total order amount is less than  the minimum value for delivery", comment: nil) }

      /// en translation: No Data Found
      ///
      /// Key: no_data_found
      ///
      /// Locales: en, ar
      var no_data_found: RswiftResources.StringResource { .init(key: "no_data_found", tableName: "Localizable", source: source, developmentValue: "No Data Found", comment: nil) }

      /// en translation: Not acctivated account
      ///
      /// Key: not_active_account
      ///
      /// Locales: en, ar
      var not_active_account: RswiftResources.StringResource { .init(key: "not_active_account", tableName: "Localizable", source: source, developmentValue: "Not acctivated account", comment: nil) }

      /// en translation: Brand Not Found
      ///
      /// Key: not_found_brand
      ///
      /// Locales: en, ar
      var not_found_brand: RswiftResources.StringResource { .init(key: "not_found_brand", tableName: "Localizable", source: source, developmentValue: "Brand Not Found", comment: nil) }

      /// en translation: Phone number not found
      ///
      /// Key: number_not_found
      ///
      /// Locales: en, ar
      var number_not_found: RswiftResources.StringResource { .init(key: "number_not_found", tableName: "Localizable", source: source, developmentValue: "Phone number not found", comment: nil) }

      /// en translation: Online Order Not available at this time
      ///
      /// Key: online_order_not_availble
      ///
      /// Locales: en, ar
      var online_order_not_availble: RswiftResources.StringResource { .init(key: "online_order_not_availble", tableName: "Localizable", source: source, developmentValue: "Online Order Not available at this time", comment: nil) }

      /// en translation: Passwords do not match.
      ///
      /// Key: password_not_match
      ///
      /// Locales: en, ar
      var password_not_match: RswiftResources.StringResource { .init(key: "password_not_match", tableName: "Localizable", source: source, developmentValue: "Passwords do not match.", comment: nil) }

      /// en translation: Password not Match with your current one
      ///
      /// Key: password_not_match_to_current
      ///
      /// Locales: en, ar
      var password_not_match_to_current: RswiftResources.StringResource { .init(key: "password_not_match_to_current", tableName: "Localizable", source: source, developmentValue: "Password not Match with your current one", comment: nil) }

      /// en translation: Phone Number already exists
      ///
      /// Key: phone_number_exist
      ///
      /// Locales: en, ar
      var phone_number_exist: RswiftResources.StringResource { .init(key: "phone_number_exist", tableName: "Localizable", source: source, developmentValue: "Phone Number already exists", comment: nil) }

      /// en translation: This code was used before or may be expired
      ///
      /// Key: qr_code_expired_or_used_before
      ///
      /// Locales: en, ar
      var qr_code_expired_or_used_before: RswiftResources.StringResource { .init(key: "qr_code_expired_or_used_before", tableName: "Localizable", source: source, developmentValue: "This code was used before or may be expired", comment: nil) }

      /// en translation: Select From %@ min: %@ max: %@
      ///
      /// Key: select_choice_msg
      ///
      /// Locales: en, ar
      var select_choice_msg: RswiftResources.StringResource3<String, String, String> { .init(key: "select_choice_msg", tableName: "Localizable", source: source, developmentValue: "Select From %@ min: %@ max: %@", comment: nil) }

      /// en translation: Please select size
      ///
      /// Key: select_size
      ///
      /// Locales: en, ar
      var select_size: RswiftResources.StringResource { .init(key: "select_size", tableName: "Localizable", source: source, developmentValue: "Please select size", comment: nil) }

      /// en translation: User not found!
      ///
      /// Key: user_not_found
      ///
      /// Locales: en, ar
      var user_not_found: RswiftResources.StringResource { .init(key: "user_not_found", tableName: "Localizable", source: source, developmentValue: "User not found!", comment: nil) }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Customer.plist`.
    var customerPlist: RswiftResources.FileResource { .init(name: "Customer", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }
}
